name: Deploy Interactive Editor to GitHub Pages

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build interactive editor
        run: npm run build:docs

      - name: Prepare subfolder for dev branch
        if: github.ref == 'refs/heads/dev'
        # Move built files to a subfolder to avoid overwriting the main docs for the master branch
        run: |
          mkdir temp_dist
          mv docs/* temp_dist/ 2>/dev/null || true
          mkdir -p docs/dev
          mv temp_dist/* docs/dev/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          keep_files: true
